### ISSUE TITLE
Error starting the docker image with a user other than root or 1000

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#135]
**Describe the bug**
When starting the docker image with a user other than root or 1000 the container will not start.

**To Reproduce**
1. Have a user other than root and 1000 on your system.
2. Check out the sources.
3. Make sure to have a valid `./data` and `./settings` folder.
4. Use the following docker compose file in the sources:
   ```yml
   version: "3.8"

   services:
     fluid:
       container_name: "fluid-queue"
       build:
         context: .
       volumes:
         - ./settings:/home/node/settings
         - ./data:/home/node/data
       restart: unless-stopped
       user: 1001:1002
   ```
5. Change the `1001:1002` to the user id and user group of the user from step (1).
  (In my case the user 1001 is `test` and the group 1002 is `test`)
6. Run `docker compose up`.

**Expected behavior**
The queue starts with users other than `root` or `1000:1000`; for example `1001:1002`.

**Log output**
```
fluid-queue  | 
fluid-queue  | > fluid-queue@2.0.0-beta.3 start
fluid-queue  | > node --enable-source-maps ./build/index.js
fluid-queue  | 
fluid-queue  | npm ERR! code EACCES
fluid-queue  | npm ERR! syscall mkdir
fluid-queue  | npm ERR! path /.npm
fluid-queue  | npm ERR! errno -13
fluid-queue  | npm ERR! 
fluid-queue  | npm ERR! Your cache folder contains root-owned files, due to a bug in
fluid-queue  | npm ERR! previous versions of npm which has since been addressed.
fluid-queue  | npm ERR! 
fluid-queue  | npm ERR! To permanently fix this problem, please run:
fluid-queue  | npm ERR!   sudo chown -R 1001:1002 "/.npm"
fluid-queue  | 
fluid-queue  | npm ERR! Log files were not written due to an error writing to the directory: /.npm/_logs
fluid-queue  | npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
fluid-queue exited with code 0
```

**Docker (please complete the following information):**

- Have you pulled the latest container updates?
  I have used the sources of `dev/node-upgrade-lts-20`: 5e9068f77618b84c6976782c0c47a171fdff8197
- Your Docker command line, or a link to a [https://gist.github.com](gist) of your Compose file:
 See `To Reproduce`.

**Desktop (please complete the following information):**

- OS: Windows 10
- Node version: N/A

**Additional context**
There is a way to fix this bug by not using `npm`, but instead `node`.
For example by changing the `docker-compose.yml` file:
```yml
version: "3.8"

services:
  fluid:
    container_name: "fluid-queue"
    build:
      context: .
    command: node --enable-source-maps ./build/index.js
    volumes:
      - ./settings:/home/node/settings
      - ./data:/home/node/data
    restart: unless-stopped
    user: 1001:1002
```
or by changing the end of the `Dockerfile`:
```
# Run the bot, no need for an entrypoint script
CMD [ "node", "--enable-source-maps", "./build/index.js"]
```
